### ISSUE TITLE
Refonte récupération des input

### ISSUE THREAD

**Issue by manalaf** [DDorch/jacase#1]
Stocker les données dans un objet par exemple v dans lequel on aura :  ` v['Q'], v['D']...`

**Comment by DDorch** [comment]
Utiliser [le data binding `[(ngModel)]`](https://angular.io/docs/ts/latest/guide/template-syntax.html#ngModel) pour faire correspondre les valeurs de l'objet v avec les inputs du formulaire.

**Comment by DDorch** [comment]
Testé avec succès sur ff60efd16fefaa6c81900efe14e2ae54afb5f562
