### ISSUE TITLE
Les codes de génération du graphique ne sont pas dans la classe Formulaire

### ISSUE THREAD

**Issue by DDorch** [DDorch/jacase#12]
La méthode `calculer ` de la classe `FormCondDistri` contient le code générant le graphique. Ce code, valable quelque soit la calculette devrait se trouver dans la classe `Formulaire`.

En fait, il ne devrait pas y avoir du tout de méthode `calculer `dans la classe `FormCondDistri`. Je propose de modifier un peu la sémantique afin d'avoir quelque chose de générique et non redondant.

Dans la classe `Formulaire`, il faut une méthode `getResult`qui sera appelée à partir du bouton du formulaire. Cette méthode se chargera de mettre en forme les données d'entrée en appelant `this.initV` et lancera le calcul en appelant la méthode `this.calculate` dans la classe Formulaire cette méthode sera déclarée avec un code vide ou minimaliste (ex : `return null`) et elle sera redéfinie dans `FormCondDistri` avec l'actuel code de la méthode `calCondDistri`.

**Comment by DDorch** [comment]
Pour répondre à la conversation qui a malencontreusement eu lieu dans #10.

La décoration de classe `@component` de la classe parent `Formulaire` est ignorée par Angular2. C'est une limitation du langage que j'ai évoqué dans #11.

Donc à moins d'essayer la solution évoquée dans #11, il faut que `@component` et la déclaration des directives soient dans la classe enfant.

**Comment by manalaf** [comment]
Donc sur index.html on doit appeler le selector de la classe enfant et non pas celle de la classe mère : <form_cond> Loading .. </form_cond>.

**Comment by DDorch** [comment]
Sauf que le nom du selector reste toujours le même quelque soit la calculette choisie. Je propose qu'on appelle le selector `<jacase>`, ça évitera toute confusion.
