### ISSUE TITLE
Tous les résultats sont à zéro

### ISSUE THREAD

**Issue by DDorch** [DDorch/jacase#14]
Test réalisé à partir du commit b9245181df4ceff9baa63d547dfbbd337a8f002f.

Quelque soit le calcul effectué le résultat est toujours nul.

Exemple : 

<table style="width:600px;float:left" cols="2">
      <tbody><tr><b>
        <td> Paramètres fixés </td>
        <td> Valeurs </td>
      </b></tr>
      <tr>
        <td> Q  : Débit (m³/s) </td>
        <td> 3.000 </td>
      </tr><tr>
        <td> J  : Perte de charge (m) </td>
        <td> 0.600 </td>
      </tr><tr>
        <td> Lg  : Longueur du tuyau (m) </td>
        <td> 100.000 </td>
      </tr><tr>
        <td> nu  : Viscosité dynamique (Pa·s) </td>
        <td> 0.000 </td>
      </tr>
      <tr>
        <td><b>D : Diamètre du tuyau (m) </b></td>
        <td> <b>0.000</b> </td>
      </tr></tbody>    
    </tbody></table>

**Comment by manalaf** [comment]
Oui en effet, c'est à cause de la template que j'avais mise dans la classe mère. Et donc il reconnait pas la classe, c'est le problème déja évoqué auparavant. Je n'ai pas fait un dernier commit.
