### ISSUE TITLE
Erreur de compilation suite au commit 596d0f9

### ISSUE THREAD

**Issue by DDorch** [DDorch/jacase#19]
Je n'arrive pas à faire fonctionner le code après ce commit. J'ai un erreur : 

```
Error: Uncaught (in promise): TypeError: dep is null
Trace de la pile :
resolvePromise@http://localhost:3000/node_modules/zone.js/dist/zone.js:538:32
scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:574:18
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:356:24
NgZoneImpl/this.inner<.onInvokeTask@http://localhost:3000/node_modules/@angular/core/core.umd.js:6066:36
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:355:24
Zone</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:256:29
drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:474:26
ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:426:22
 zone.js:463:10
```

J'ai l'impression qu'il y a un problème de dépendance avec le module router. Lors de l'installation, il y a des dépendances non assurées : 

```
$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/router@3.0.0-beta.2 requires a peer of @angular/core@^2.0.0-rc.4 but none was installed.
npm WARN @angular/router@3.0.0-beta.2 requires a peer of @angular/compiler@^2.0.0-rc.4 but none was installed.
npm WARN @angular/router@3.0.0-beta.2 requires a peer of @angular/common@^2.0.0-rc.4 but none was installed.
npm WARN @angular/router@3.0.0-beta.2 requires a peer of @angular/platform-browser@^2.0.0-rc.4 but none was installed.
npm WARN @angular/router@3.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@^2.0.0-rc.4 but none was installed.
npm WARN jacase@0.1.0 No repository field.
```

Le router choisi nécessite la version 2.0.0-rc4 d'Angular, et c'est la version rc1 qui est configurée dans  package.json.

**Comment by DDorch** [comment]
J'ai mis à jour la version d'angular dans package.json vers la version 2.0.0-rc4. Il y avait un problème de dépendance pour angular2-in-memory-web-api que j'ai upgradé à la dernière version (0.0.14).

Ensuite, j'ai eu une erreur : `Error loading http://localhost:3000/node_modules/@angular/platform-browser-dynamic/platform-browser-dynamic.umd.js`

Que j'ai résolu grâce à http://www.dakehe.info/blog/post/angular2-try-quickstart-from-angulario en modifiant systemjs.config.js.

Il y a encore une erreur au démarrage : `EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: ''` mais ensuite, les calculettes se chargent correctement lorsqu'on clique dessus.

**Comment by manalaf** [comment]
La compilation marchait bien pour moi. 
Quand j'ai fait le git pull, la page ne se charge pas du tout. J'ai eu l'erreur suivante:
`GET XHR http://localhost:3000/node_modules/@angular/platform-browser-dynamic//bundles/platform-browser-dynamic.umd.js [HTTP/1.1 404 Not Found 1 ms]
GET XHR http://localhost:3000/node_modules/@angular/http//bundles/http.umd.js [HTTP/1.1 404 Not Found 1 ms]
Error: patchProperty/desc.set/wrapFn@http://localhost:3000/node_modules/zone.js/dist/zone.js:769:27
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:256:29
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:423:29
	
	Error loading http://localhost:3000/node_modules/@angular/platform-browser-dynamic//bundles/platform-browser-dynamic.umd.js as "@angular/platform-browser-dynamic" from http://localhost:3000/app/boot.js`

**Comment by manalaf** [comment]
Le compilateur ne retrouve plus les .umd.js après le changement fait au `function packUmd(pkgName)`

**Comment by manalaf** [comment]
En la modifiant `function packUmd(pkgName)` par la version antérieure, ça remarche.

**Comment by DDorch** [comment]
Juste une question, comme j'ai modifié le package.json, est-ce que tu avais fait `npm install` ?

**Comment by manalaf** [comment]
Oui mais le compilateur a du mal à reconnaitre le `/bundles/`

**Comment by manalaf** [comment]
Du coup j'ai remis cela :
`function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main:  pkgName + '.umd.js', defaultExtension: 'js' };
  };`

**Comment by DDorch** [comment]
Chez moi depuis, que j'ai mis à jour angular de la version rc1 à la version rc4, j'ai besoin pour que le code fonctionne de la modification apportée fichier systemjs.config.js au commit c4aadb8 et que tu as enlevé au commit 9e3d3e04f877ce3c4527d5bc5e23df56a202d1c5.

C'est une modification qu'on retrouve sur le dépôt qui héberge l'exemple Quick Start d'Angular2 et qui a été mis en œuvre à la sortie de la rc2 : https://github.com/angular/quickstart/commit/6e430b276099340766b98def91c1a2b628f93465#diff-e86973cdb7894730814fdc0868f16063

A ce propos, il y a une erreur dans cette modification : il y a un slash de trop avant "bundle". Il y a une issue en cours de résolution là-dessus (https://github.com/angular/angular/issues/9871). 

Je me rends compte que ça peut être un peu perturbant de travailler avec un langage qui est encore en développement...

**Comment by manalaf** [comment]
J'avais déjà essayé d'enlever le slash de trop après le git pull mais ça ne marchait toujours pas chez moi.

**Comment by DDorch** [comment]
As-tu essayé en remettant ton installation à zéro ? C'est-à-dire en effaçant le contenu du dossier node_modules et en refaisant un `npm install` ?

**Comment by manalaf** [comment]
Oui c'est bon ça a marché.
