### ISSUE TITLE
Format des nombres pour les résultats

### ISSUE THREAD

**Issue by DDorch** [DDorch/jacase#8]
Il faut utiliser les pipes.

Pour avoir un format avec 3 décimales fixes, la syntaxe est la suivante : `{{result|number:'.3-3'}}`

Pour paramétrer, le nombre de décimales en fonction de la valeur du champ "Précision de calcul", le plus propre a l'air de créer notre propre pipe (Voir http://voidcanvas.com/angular-2-pipes-filters/#designing-the-pipe).

Dans la version PHP, on effectuait la transformation suivante pour récupérer le nombre de décimales à partir de la valeur du champ : `$data['iPrec']=(int)-log10(_request('rPrec'));` (cf. http://zone.spip.org/trac/spip-zone/browser/_plugins_/hydraulic/trunk/hyd_inc/formulaire.abstract.class.php#L194).

**Comment by DDorch** [comment]
Question résolue avec les commits 2289487e1207efa289dacbc853a797ec86476684 et 24682cd1140db39be0358f2202c5f15febb1507c.

**Comment by DDorch** [comment]
Le paramétrage de la précision d'affichage à partir du champ précision n'est pas effectif.

**Comment by manalaf** [comment]
J'ai eu des soucis avec le commit. En essayant de regler le problème j'ai supprimé ce que j'ai modifié depuis le dernier commit sans m'en rendre compte ..
Je ferai le commit demain matin quand tout sera reglé.
